export const faseE_materi = [
  {
    id: "chap_1",
    title: "Pengantar Ilmu Sejarah",
    summary: "Memahami hakikat, ruang lingkup, konsep waktu, ruang, dan manusia dalam sejarah serta metodologi penelitian sejarah.",
    contentByLevel: {
      0: `<h2>Pengertian dan Ruang Lingkup Ilmu Sejarah</h2>
      <p>Sejarah adalah jembatan yang menghubungkan masa lalu dengan masa kini. Kata 'sejarah' dalam bahasa Indonesia berasal dari bahasa Arab <em>syajarotun</em> yang berarti 'pohon'. Mengapa pohon? Karena pohon memiliki akar yang kuat menghujam ke bumi (masa lalu), batang yang tegak berdiri (masa kini), dan cabang yang terus tumbuh berkembang (masa depan). Peristiwa sejarah tidak pernah berdiri sendiri, ia selalu berkaitan dan memiliki sebab-akibat yang membentuk rantai waktu.</p>
      <p>Menurut bapak sejarah dunia, Herodotus, sejarah tidak berkembang ke arah depan dengan tujuan pasti, melainkan bergerak seperti garis lingkaran yang tinggi rendahnya diakibatkan oleh keadaan manusia itu sendiri. Sedangkan Ibnu Khaldun memandang sejarah sebagai catatan tentang masyarakat umat manusia atau peradaban dunia, tentang perubahan-perubahan yang terjadi pada watak masyarakat tersebut.</p>
      <p>Dalam ilmu sejarah, terdapat tiga unsur esensial yang tidak terpisahkan: Manusia, Ruang, dan Waktu. Manusia adalah aktor atau subjek utama penggerak sejarah. Tanpa manusia, tidak akan ada sejarah. Ruang merujuk pada aspek geografis atau lokasi di mana peristiwa itu terjadi, yang memberikan warna dan karakteristik khusus pada sebuah peristiwa. Sedangkan waktu adalah dimensi temporal yang menunjukkan kapan peristiwa itu berlangsung. Waktu dalam sejarah terbagi menjadi empat konsep: perkembangan, kesinambungan, pengulangan, dan perubahan.</p>`,
      1: `<h2>Konsep Berpikir Sejarah: Diakronik dan Sinkronik</h2>
      <p>Untuk memahami kompleksitas masa lalu, sejarawan menggunakan berbagai pendekatan berpikir. Dua pendekatan utama adalah Diakronik dan Sinkronik.</p>
      <p><strong>Berpikir Diakronik (Kronologis)</strong><br/>
      Kata diakronik berasal dari bahasa Yunani 'dia' (melalui) dan 'chronos' (waktu). Berpikir diakronik berarti memanjang dalam waktu tetapi menyempit dalam ruang. Pendekatan ini sangat mementingkan urutan kejadian secara kronologis untuk melihat proses perubahan dan perkembangan suatu peristiwa dari waktu ke waktu. Contoh: Menganalisis sejarah Perang Diponegoro dari tahun 1825 hingga 1830 secara berurutan. Ini mencegah kita terjebak dalam anakronisme (penempatan peristiwa atau tokoh yang tidak sesuai dengan zamannya).</p>
      <p><strong>Berpikir Sinkronik (Ilmu Sosial)</strong><br/>
      Sebaliknya, sinkronik berarti meluas dalam ruang tetapi menyempit dalam waktu. Pendekatan ini sering meminjam pisau analisis dari ilmu-ilmu sosial lain seperti sosiologi, antropologi, politik, dan ekonomi. Tujuannya adalah untuk membedah suatu peristiwa pada satu titik waktu tertentu secara mendalam. Contoh: Mengkaji struktur sosial, kondisi ekonomi, dan sistem politik masyarakat Jawa pada tahun 1825 tepat sebelum Perang Diponegoro meletus.</p>
      <p>Penggabungan kedua cara berpikir ini menghasilkan historiografi yang komprehensif, di mana urutan waktu terjaga dengan baik, namun kedalaman analisis sosialnya juga tajam.</p>`,
      2: `<h2>Metodologi Penelitian Sejarah dan Kritik Sumber</h2>
      <p>Bagaimana sebuah peristiwa masa lalu bisa diyakini kebenarannya? Di sinilah peran metodologi penelitian sejarah. Proses ini harus dilalui oleh setiap sejarawan untuk mengubah 'sumber' menjadi 'fakta' sejarah. Terdapat empat tahapan utama:</p>
      <p><strong>1. Heuristik (Pengumpulan Sumber)</strong><br/>
      Tahap awal di mana sejarawan mencari dan mengumpulkan jejak-jejak masa lalu. Sumber bisa berupa sumber tertulis (dokumen, prasasti), lisan (wawancara pelaku sejarah), dan benda/artefak (candi, senjata). Heuristik menuntut sejarawan untuk pergi ke arsip, perpustakaan, atau situs purbakala.</p>
      <p><strong>2. Verifikasi (Kritik Sumber)</strong><br/>
      Tidak semua sumber bisa langsung dipercaya. Harus ada kritik ekstern (menguji keaslian fisik sumber: apakah kertasnya benar dari abad ke-19? apakah tintanya sesuai?) dan kritik intern (menguji kredibilitas isi: apakah penulis memiliki bias tertentu? apakah informasi ini masuk akal?).</p>
      <p><strong>3. Interpretasi (Penafsiran)</strong><br/>
      Setelah sumber diverifikasi menjadi fakta yang valid, sejarawan mulai merangkai fakta-fakta tersebut. Interpretasi menghubungkan satu fakta dengan fakta lain sehingga membentuk sebuah narasi yang logis. Di tahap ini, subjektivitas sejarawan seringkali tidak dapat dihindari sepenuhnya.</p>
      <p><strong>4. Historiografi (Penulisan Sejarah)</strong><br/>
      Tahap puncak di mana hasil penelitian ditulis menjadi sebuah karya sejarah (buku, jurnal). Historiografi membutuhkan kemampuan bahasa dan sastra agar narasi yang disajikan tidak hanya faktual, tetapi juga dapat dinikmati oleh pembacanya.</p>`,
      3: `<h2>Perkembangan Historiografi Indonesia</h2>
      <p>Penulisan sejarah di Indonesia tidaklah statis; ia berevolusi seiring dengan perubahan paradigma sosial dan politik bangsa. Secara garis besar, historiografi di Indonesia dibagi menjadi tiga fase utama:</p>
      <p><strong>1. Historiografi Tradisional</strong><br/>
      Berkembang pada masa kerajaan Hindu-Buddha hingga Islam. Karakteristik utamanya adalah istanasentris (berpusat pada kehidupan raja/istana), magis-religius (raja dianggap titisan dewa atau memiliki kesaktian), dan seringkali tidak terlalu ketat dalam kronologi waktu. Tujuannya lebih kepada melegitimasi kekuasaan raja daripada mencatat fakta objektif. Contoh: Babad Tanah Jawi, Kitab Negarakertagama, Hikayat Raja-Raja Pasai.</p>
      <p><strong>2. Historiografi Kolonial</strong><br/>
      Masa penjajahan Barat melahirkan historiografi kolonial yang bersifat Neerlandsentris (berpusat pada kepentingan Belanda). Dalam pandangan ini, orang Belanda dianggap sebagai pahlawan dan pembawa peradaban, sedangkan tokoh-tokoh lokal yang melawan (seperti Diponegoro, Imam Bonjol) dilabeli sebagai pemberontak atau pengkhianat. Sejarah ditulis berdasarkan arsip-arsip resmi pemerintah Hindia Belanda.</p>
      <p><strong>3. Historiografi Modern (Nasional)</strong><br/>
      Pasca kemerdekaan, muncul kesadaran untuk mendekolonisasi narasi sejarah. Seminar Sejarah Nasional Pertama tahun 1957 di Yogyakarta menjadi tonggak kebangkitan historiografi nasional yang Indonesiasentris. Tokoh-tokoh lokal mulai ditempatkan sebagai subjek dan pahlawan. Pendekatan multidimensional (menggunakan ilmu bantu sosial) mulai diterapkan secara masif berkat pelopor seperti Prof. Sartono Kartodirdjo dalam karyanya "Pemberontakan Petani Banten 1888", yang menggeser fokus dari elit politik ke sejarah rakyat kecil (sejarah sosial).</p>`
    }
  },
  {
    id: "chap_2",
    title: "Asal Usul Nenek Moyang dan Jalur Rempah",
    summary: "Penelusuran jejak manusia praaksara, teori migrasi nenek moyang bangsa Indonesia, dan peran Nusantara dalam jaringan perdagangan rempah prasejarah.",
    contentByLevel: {
      0: `<h2>Mengenal Manusia Purba di Nusantara</h2>
      <p>Jauh sebelum peradaban modern lahir, kepulauan Indonesia telah menjadi rumah bagi spesies manusia purba. Kondisi geografis Nusantara yang strategis dan subur menjadikannya salah satu situs penemuan fosil manusia purba terlengkap di dunia, sehingga Indonesia sering dijuluki "Museum Manusia Purba Dunia". Sangiran, sebuah wilayah di Jawa Tengah, bahkan telah diakui oleh UNESCO sebagai Warisan Dunia karena menyimpan lebih dari 50% fosil <em>Homo erectus</em> di bumi.</p>
      <p>Beberapa jenis manusia purba yang pernah hidup di Indonesia antara lain:</p>
      <p><strong>1. Meganthropus Palaeojavanicus:</strong> Manusia raksasa tertua dari Jawa yang ditemukan oleh von Koenigswald di Sangiran. Mereka memiliki rahang yang sangat besar dan kuat untuk mengunyah makanan yang masih mentah (akar-akaran dan tumbuhan).</p>
      <p><strong>2. Pithecanthropus Erectus:</strong> Ditemukan oleh Eugene Dubois di Trinil, Ngawi. Arti namanya adalah "manusia kera yang berjalan tegak". Ini adalah spesies yang paling banyak ditemukan di Indonesia dan dianggap sebagai missing link dalam teori evolusi awal.</p>
      <p><strong>3. Homo Sapiens:</strong> Manusia cerdas yang volume otaknya sudah menyamai manusia modern. Contohnya adalah Homo Soloensis dan Homo Wajakensis. Mereka sudah mampu membuat peralatan yang lebih halus dan mengenal sistem kepercayaan sederhana.</p>`,
      1: `<h2>Teori Migrasi dan Asal-Usul Bangsa Indonesia</h2>
      <p>Darimana asal mula penduduk asli kepulauan Indonesia saat ini? Terdapat beberapa teori besar yang diperdebatkan oleh para ahli sejarah, antropolog, dan pakar linguistik:</p>
      <p><strong>1. Teori Yunan:</strong> Didukung oleh J.H.C. Kern dan Robert von Heine Geldern. Teori ini menyatakan bahwa nenek moyang bangsa Indonesia berasal dari daerah Yunan di Cina Selatan. Buktinya adalah kesamaan kapak tua yang ditemukan di Nusantara dengan kapak di Asia Tengah, serta kemiripan kebahasaan.</p>
      <p><strong>2. Teori Nusantara:</strong> Didukung oleh Mohammad Yamin dan Gorys Keraf. Menyatakan bahwa bangsa Indonesia tidak berasal dari mana-mana, melainkan penduduk asli kepulauan ini yang berevolusi. Argumen utamanya adalah penemuan fosil <em>Homo soloensis</em> dan <em>Homo wajakensis</em> yang sangat banyak di Indonesia.</p>
      <p><strong>3. Teori Out of Taiwan:</strong> Teori kontemporer yang didukung oleh Peter Bellwood. Secara linguistik, seluruh bahasa di Nusantara berakar pada rumpun Austronesia yang bermigrasi dari Formosa (Taiwan) sekitar 4000-3000 SM. Mereka bergerak ke Filipina, lalu ke kepulauan Indonesia, membawa budaya maritim dan agrikultur (bercocok tanam padi).</p>
      <p><strong>4. Teori Out of Africa:</strong> Berdasarkan tes DNA mitokondria (genetika modern), manusia modern (Homo sapiens) berasal dari Afrika yang kemudian menyebar ke seluruh penjuru dunia sekitar 50.000 hingga 70.000 tahun yang lalu, menyusuri garis pantai Samudra Hindia hingga tiba di Nusantara dan Australia.</p>`,
      2: `<h2>Dinamika Gelombang Migrasi Austronesia</h2>
      <p>Berdasarkan pendekatan arkeologis dan antropologis, perpindahan rumpun bangsa Austronesia ke wilayah Nusantara tidak terjadi secara serentak, melainkan melalui beberapa gelombang besar yang masing-masing membawa peradaban material yang berbeda.</p>
      <p><strong>1. Bangsa Papua Melanesoid</strong><br/>Mereka adalah penduduk awal yang memiliki ciri fisik ras Negroid. Mereka bergeser ke wilayah Indonesia bagian Timur (Papua, Kepulauan Kei) akibat terdesak oleh gelombang kedatangan bangsa Melayu. Kebudayaan mereka tergolong dalam masa berburu dan meramu (Mesolitikum).</p>
      <p><strong>2. Bangsa Proto Melayu (Melayu Tua)</strong><br/>Bermigrasi sekitar 1500 SM. Mereka masuk melalui dua jalur: Jalur Barat (Malaya - Sumatera - Jawa) membawa kebudayaan kapak persegi, dan Jalur Timur (Filipina - Sulawesi) membawa kebudayaan kapak lonjong. Keturunan Proto Melayu yang masih ada hingga kini antara lain Suku Batak, Toraja, Sasak, dan Dayak. Kebudayaan mereka masih berpusat pada peralatan dari batu (Neolitikum).</p>
      <p><strong>3. Bangsa Deutero Melayu (Melayu Muda)</strong><br/>Bermigrasi sekitar 500 SM. Gelombang ini jauh lebih maju karena mereka telah menguasai teknologi pengolahan logam (perunggu dan besi), yang dikenal sebagai kebudayaan Dongson. Mereka ahli membuat nekara, kapak corong, dan perhiasan perunggu. Keturunan mereka adalah sebagian besar penduduk Indonesia modern seperti Suku Jawa, Sunda, Bugis, dan Minang.</p>`,
      3: `<h2>Jalur Rempah: Jaringan Perdagangan Prasejarah Nusantara</h2>
      <p>Lama sebelum bangsa Eropa mencari rempah-rempah pada abad ke-16, Nusantara telah menjadi episentrum dari sebuah jaringan perdagangan global yang membentang dari Kepulauan Maluku hingga ke Timur Tengah dan Eropa. Jaringan pelayaran dan perniagaan purba ini dikenal sebagai <strong>Jalur Rempah (Spice Route)</strong>.</p>
      <p>Pada masa praaksara (zaman logam), kemampuan navigasi maritim nenek moyang kita sudah sangat mumpuni. Mereka menciptakan kapal bercadik ganda (outrigger) yang sangat stabil menerjang ombak samudra. Perjalanan mereka mengandalkan pengetahuan astronomi dan pola angin monsun.</p>
      <p>Rempah-rempah seperti cengkeh dari Ternate-Tidore dan pala dari Kepulauan Banda adalah komoditas eksklusif endemik yang saat itu tidak bisa ditemukan di tempat lain di dunia. Bukti awal keberadaan Jalur Rempah purba adalah penemuan sisa cengkeh di situs Terqa, Suriah, yang berasal dari tahun 1700 SM. Ini membuktikan bahwa komoditas dari ujung timur Indonesia telah menjangkau peradaban Mesopotamia ribuan tahun sebelum masehi.</p>
      <p>Jalur Rempah tidak hanya berfungsi sebagai medium ekonomi perpindahan barang, tetapi juga bertindak sebagai wadah asimilasi budaya, penyebaran bahasa, dan pertukaran sistem kepercayaan. Pelabuhan-pelabuhan transito di Jawa dan Sumatera menjadi tempat bertemunya berbagai peradaban. Inilah fondasi awal yang membentuk karakter bangsa Indonesia sebagai bangsa maritim yang terbuka, kosmopolit, dan multikultural.</p>`
    }
  },
  {
    id: "chap_3",
    title: "Masa Kerajaan Hindu-Buddha",
    summary: "Sejarah masuknya pengaruh agama dan kebudayaan Hindu-Buddha, proses akulturasi, serta berdirinya kerajaan-kerajaan besar Nusantara.",
    contentByLevel: {
      0: `<h2>Awal Masuknya Pengaruh Hindu-Buddha</h2>
      <p>Pada awal abad Masehi, kepulauan Nusantara mulai menjalin hubungan dagang yang intensif dengan dua peradaban besar dunia: India dan Tiongkok. Para pedagang yang melewati Selat Malaka harus singgah berbulan-bulan di pesisir Nusantara menunggu perubahan arah angin monsun. Interaksi panjang ini membawa dampak besar, tidak hanya pada komoditas dagang, tetapi juga masuknya agama, sistem tulisan (Pallawa), bahasa (Sanskerta), dan konsep ketatanegaraan Hindu-Buddha.</p>
      <p>Terdapat beberapa teori mengenai siapa yang membawa budaya India ini ke Indonesia. Ada Teori Waisya (oleh pedagang), Teori Ksatria (oleh prajurit yang kalah perang), Teori Brahmana (oleh para pendeta yang diundang raja lokal), dan Teori Arus Balik (orang Nusantara sendiri yang belajar ke India dan membawanya pulang). Teori Brahmana (oleh J.C. van Leur) dan Teori Arus Balik (oleh F.D.K. Bosch) dianggap paling kuat karena ajaran Hindu tingkat tinggi dan bahasa Sanskerta hanya dikuasai oleh kaum Brahmana.</p>
      <p>Masuknya budaya ini mengubah struktur sosial Nusantara. Dari yang awalnya dipimpin oleh kepala suku (primus interpares), berubah menjadi kerajaan yang dipimpin oleh Raja. Raja dianggap sebagai titisan dewa di bumi (konsep Dewaraja).</p>`,
      1: `<h2>Kerajaan Maritim dan Agraris Klasik</h2>
      <p>Kerajaan Hindu-Buddha di Nusantara terbagi menjadi dua corak utama berdasarkan basis ekonominya: Maritim dan Agraris.</p>
      <p><strong>Kerajaan Maritim: Sriwijaya</strong><br/>
      Kerajaan bercorak Buddha yang berpusat di Palembang (Sumatera) ini mencapai puncak kejayaan pada abad ke-8 dan 9. Sriwijaya adalah penguasa mutlak jalur perdagangan laut di Selat Malaka dan Selat Sunda. Mereka mewajibkan kapal asing untuk singgah dan membayar pajak. Kekayaan ekonomi ini membuat Sriwijaya mampu menjadi pusat pendidikan agama Buddha terbesar di Asia Tenggara. Biksu terkenal dari Tiongkok, I-Tsing, pernah bermukim dan menerjemahkan kitab suci di sana bersama mahaguru Dharmakirti.</p>
      <p><strong>Kerajaan Agraris: Mataram Kuno</strong><br/>
      Berbeda dengan Sriwijaya, Mataram Kuno (Bumi Mataram) di pedalaman Jawa Tengah mengandalkan hasil pertanian pangan karena tanah vulkanisnya yang sangat subur. Kerajaan ini dikuasai oleh dua wangsa besar: Sanjaya (Hindu) dan Syailendra (Buddha). Meskipun berbeda agama, mereka dapat hidup berdampingan secara damai. Puncak manifestasi toleransi ini adalah pembangunan mahakarya arsitektur, yaitu Candi Borobudur oleh Wangsa Syailendra dan Candi Prambanan oleh Wangsa Sanjaya.</p>`,
      2: `<h2>Puncak Kejayaan: Imperium Majapahit</h2>
      <p>Kerajaan Hindu-Buddha terbesar dan terakhir yang menyatukan Nusantara adalah Majapahit (1293 - 1527 M). Majapahit didirikan oleh Raden Wijaya setelah dengan cerdik memanfaatkan tentara Mongol (Dinasti Yuan) untuk mengalahkan saingannya, Jayakatwang, dan kemudian mengusir tentara Mongol dari Jawa.</p>
      <p>Majapahit mencapai masa keemasannya pada masa pemerintahan Raja Hayam Wuruk dengan dibantu oleh Mahapatih Gajah Mada. Gajah Mada terkenal dengan <strong>Sumpah Palapa</strong>-nya yang ikonik: "Lamun huwus kalah Nusantara isun amukti palapa...". Sumpah ini berisi tekad untuk tidak akan beristirahat (menikmati palapa/kenikmatan duniawi) sebelum berhasil menyatukan seluruh wilayah Nusantara (termasuk Gurun, Seran, Tanjungpura, Haru, Pahang, Dompo, Bali, Sunda, Palembang, dan Tumasik).</p>
      <p>Secara ekonomi, Majapahit memadukan kekuatan agraris di wilayah pedalaman Jawa (dengan sistem irigasi sungai Brantas) dan kekuatan maritim di pesisir utara Jawa. Majapahit memiliki armada laut yang kuat di bawah pimpinan Mpu Nala untuk menjaga rute perdagangan rempah-rempah dari Maluku hingga ke pelabuhan Tuban dan Gresik.</p>`,
      3: `<h2>Akulturasi Budaya dan Warisan Kebangsaan</h2>
      <p>Kebudayaan Hindu-Buddha yang masuk ke Nusantara tidak diterima secara mentah-mentah (cultural imperialism), melainkan mengalami proses penyaringan (filterisasi) oleh kearifan lokal yang disebut dengan <em>Local Genius</em>. Hal ini menghasilkan proses Akulturasi (perpaduan dua budaya tanpa menghilangkan unsur aslinya).</p>
      <p><strong>Bukti Akulturasi dalam Arsitektur:</strong><br/>Candi-candi di Indonesia tidak sama persis dengan yang ada di India. Candi di Nusantara adalah modifikasi dari tradisi megalitikum 'punden berundak' (tempat pemujaan roh nenek moyang). Patung-patung di candi bukan hanya wujud dewa, tetapi juga perwujudan (arca perwujudan) dari raja yang telah wafat yang disatukan dengan roh dewa utama.</p>
      <p><strong>Warisan Sastra dan Ideologi Kenegaraan:</strong><br/>Masa Majapahit meninggalkan karya sastra epik seperti Kakawin Negarakertagama karya Mpu Prapanca (memuat deskripsi tata negara dan wilayah Majapahit) dan Kakawin Sutasoma karya Mpu Tantular. Di dalam Kakawin Sutasoma inilah terdapat kalimat <em>"Bhinneka Tunggal Ika Tan Hana Dharma Mangrwa"</em> (Berbeda-beda itu, satu itu, tidak ada kebenaran yang mendua). Konsep toleransi beragama yang hidup di era Majapahit ini kemudian direvitalisasi oleh The Founding Fathers Indonesia menjadi semboyan resmi negara untuk merekatkan kemajemukan bangsa.</p>`
    }
  },
  {
    id: "chap_4",
    title: "Kerajaan Islam di Nusantara",
    summary: "Sejarah masuknya agama Islam, proses islamisasi yang damai, serta munculnya kekuatan baru kesultanan Islam di Nusantara.",
    contentByLevel: {
      0: `<h2>Masuknya Cahaya Islam di Nusantara</h2>
      <p>Setelah berabad-abad didominasi oleh peradaban Hindu-Buddha, angin perubahan bertiup dari kawasan Timur Tengah. Islam mulai masuk dan berkembang di Nusantara antara abad ke-7 hingga ke-13 Masehi. Berbeda dengan invasi militer yang terjadi di wilayah Eropa dan Asia Tengah, Islam masuk ke Indonesia dengan cara yang sangat damai melalui kontak perdagangan jalur laut yang sibuk.</p>
      <p>Pedagang-pedagang muslim dari Arab, Persia, dan Gujarat (India) yang datang berdagang rempah-rempah perlahan-lahan menetap di pesisir Sumatera dan Jawa. Mereka menikah dengan perempuan lokal dan membentuk komunitas muslim (Pekojan). Lambat laun, ajaran Islam yang sederhana (tidak mengenal kasta) mulai menarik minat penduduk lokal, dari rakyat jelata hingga akhirnya mencapai golongan bangsawan dan raja.</p>
      <p>Proses penyebaran Islam dilakukan melalui 5 saluran utama: (1) Perdagangan lintas samudra, (2) Perkawinan antara pedagang asing dengan penduduk lokal, (3) Pendidikan melalui sistem pesantren atau surau, (4) Tasawuf atau ajaran mistik Islam yang mudah diterima masyarakat lokal, dan (5) Kesenian, seperti pertunjukan wayang kulit dan tembang.</p>`,
      1: `<h2>Wali Songo dan Strategi Kultural Dakwah</h2>
      <p>Di Pulau Jawa, penyebaran Islam dilakukan secara masif dan terstruktur oleh sembilan orang ulama kharismatik yang dikenal sebagai <strong>Wali Songo</strong>. Mereka memiliki spesialisasi dan wilayah dakwah yang berbeda, namun menggunakan satu strategi yang sama: Dakwah Kultural (Cultural Approach).</p>
      <p>Para Wali tidak memberangus budaya lama Hindu-Buddha yang sudah mendarah daging, melainkan memodifikasi dan mengisinya dengan ajaran tauhid Islam. Contoh paling brilian adalah yang dilakukan oleh Sunan Kalijaga. Beliau menciptakan lakon Wayang Kulit bernafaskan Islam (seperti lakon Jamus Kalimasada yang merupakan personifikasi dari Dua Kalimat Syahadat). Sunan Kalijaga juga menggunakan Gamelan (Gamelan Sekaten) untuk menarik massa berkumpul, sebelum akhirnya memberikan wejangan agama.</p>
      <p>Sunan Kudus memiliki pendekatan yang luar biasa dalam toleransi. Beliau melarang pengikutnya menyembelih sapi (hewan suci umat Hindu) sebagai bentuk penghormatan, dan menara Masjid Kudus dibangun menyerupai bangunan bale kulkul Hindu/candi Jawa Timur. Melalui pendekatan yang humanis dan tanpa paksaan ini, Islam memenangkan hati masyarakat Jawa secara total.</p>`,
      2: `<h2>Bangkitnya Kesultanan Maritim Islam</h2>
      <p>Seiring melemahnya Majapahit dan Sriwijaya, muncul kekuatan baru berupa Kesultanan-kesultanan Islam yang menguasai jaringan maritim Nusantara.</p>
      <p><strong>1. Samudera Pasai dan Aceh Darussalam (Sumatera)</strong><br/>
      Samudera Pasai adalah kerajaan Islam pertama (berdiri abad ke-13) di utara Sumatera. Pada abad ke-16, Kesultanan Aceh menggantikannya dan mencapai masa keemasan di bawah Sultan Iskandar Muda. Aceh menjadi pusat perdagangan lada dan pusat keilmuan Islam (Serambi Mekkah), menandingi dominasi Portugis di Selat Malaka.</p>
      <p><strong>2. Kesultanan Demak (Jawa)</strong><br/>
      Sebagai pelanjut legitimasi Majapahit, Demak dipimpin oleh Raden Patah. Demak tidak hanya kuat secara agraris tetapi juga memiliki armada militer laut yang kuat. Adipati Unus (Pangeran Sabrang Lor) bahkan berani menyerang markas armada Portugis di Malaka pada tahun 1513 untuk melindungi jalur dagang Islam.</p>
      <p><strong>3. Gowa-Tallo dan Ternate-Tidore (Indonesia Timur)</strong><br/>
      Di Sulawesi, Kesultanan Gowa-Tallo (Makassar) menjadi bandar niaga (transito) terbesar yang menerapkan prinsip perdagangan bebas (Mare Liberum). Di bawah Sultan Hasanuddin, mereka gigih melawan monopoli VOC Belanda. Di Maluku, Ternate dan Tidore memimpin federasi Uli Lima dan Uli Siwa untuk memonopoli cengkeh dan pala, serta terus-menerus berperang mengusir ekspansi bangsa Spanyol dan Portugis.</p>`,
      3: `<h2>Sintesis Agama dan Hegemoni Budaya (Kerajaan Mataram Islam)</h2>
      <p>Puncak dari sinkretisme kebudayaan Jawa dan ajaran Islam terjadi pada masa <strong>Kesultanan Mataram Islam</strong>, terutama di bawah pemerintahan raja terbesarnya, Sultan Agung Hanyokrokusumo (1613-1645). Sultan Agung memiliki ambisi besar menyatukan seluruh tanah Jawa dan mengusir penjajah VOC dari Batavia.</p>
      <p>Untuk melegitimasi kekuasaannya secara absolut, Sultan Agung menggunakan gelar yang memadukan tiga dimensi sekaligus: <em>Senopati ing Ngalaga</em> (panglima perang militer), <em>Sayidin Panatagama</em> (pemimpin spiritual tertinggi Islam), dan <em>Khalifatullah</em> (wakil Tuhan di bumi, konsep sufi dan kekuasaan mutlak dewaraja lama).</p>
      <p>Sultan Agung juga berhasil menciptakan hegemoni budaya dengan menggabungkan Tarikh Hijriah (kalender Islam yang berbasis bulan) dengan Tarikh Saka (kalender Hindu-Jawa yang berbasis matahari) menjadi <strong>Kalender Jawa Islam</strong> pada tahun 1633 M (1555 Saka). Penciptaan sistem waktu yang baru ini bukan hanya sebuah inovasi astronomis, melainkan strategi politik kultural tingkat tinggi untuk menyatukan masyarakat pesisir (yang santri) dengan masyarakat pedalaman (yang sinkretis/abangan) di bawah satu otoritas sentral Keraton Mataram.</p>`
    }
  }
];
