export const faseF_materi = [
  {
    id: "chap_8",
    title: "Mempertahankan Kemerdekaan",
    summary: "Sejarah perjuangan fisik lewat Agresi Militer Belanda dan strategi diplomasi tingkat tinggi dari Linggarjati hingga KMB untuk mendapatkan kedaulatan utuh.",
    contentByLevel: {
      0: `<h2>Merdeka atau Mati! Perlawanan Rakyat Semesta</h2>
      <p>Proklamasi 17 Agustus 1945 ternyata bukanlah akhir dari perjuangan, melainkan awal dari perang yang sangat melelahkan. Mengapa? Karena Belanda (NICA) membonceng tentara Sekutu (Inggris) datang kembali ke Indonesia dengan tujuan ingin menjajah kita lagi! Mereka menganggap Indonesia masih merupakan koloni sah milik kerajaan Belanda.</p>
      <p>Rakyat Indonesia dari berbagai daerah tentu saja marah besar dan mengangkat senjata. Semboyan "Merdeka atau Mati" menggema di mana-mana. Terjadilah pertempuran dahsyat di Surabaya pada 10 November 1945 (yang kini kita peringati sebagai Hari Pahlawan). Arek-arek Suroboyo di bawah komando Bung Tomo berani melawan gempuran darat, laut, dan udara dari tentara Inggris yang baru saja memenangkan Perang Dunia.</p>
      <p>Selain di Surabaya, terjadi juga Palagan Ambarawa, Bandung Lautan Api, dan Puputan Margarana di Bali. Perjuangan rakyat ini membuktikan kepada dunia bahwa bangsa Indonesia tidak mau dijajah lagi dan rela mengorbankan nyawa demi mempertahankan kemerdekaannya.</p>`,
      1: `<h2>Strategi Diplomasi dan Agresi Militer Belanda</h2>
      <p>Selain perjuangan fisik (senjata), pemerintah Republik Indonesia menyadari bahwa kita tidak mungkin bisa menang melawan negara Barat hanya dengan otot, apalagi kita belum memiliki pabrik senjata yang memadai. Karena itu, digunakanlah strategi <strong>Diplomasi</strong>.</p>
      <p>Sutan Sjahrir (Perdana Menteri pertama kita) melakukan diplomasi yang cerdas, seperti mengirimkan bantuan beras kepada India yang sedang kelaparan (Diplomasi Beras). Hal ini membuat simpati dunia internasional mengalir ke Indonesia. Terjadilah beberapa perundingan dengan Belanda, seperti <strong>Perundingan Linggarjati</strong> dan <strong>Perundingan Renville</strong>.</p>
      <p>Namun, Belanda ternyata sangat licik. Mereka sering melanggar hasil perundingan tersebut dengan melancarkan <strong>Agresi Militer I (1947)</strong> dan <strong>Agresi Militer II (1948)</strong>. Pada Agresi Militer II, ibu kota Yogyakarta diserang secara mendadak, dan Presiden Soekarno beserta Wakil Presiden Moh. Hatta ditangkap dan diasingkan. Belanda mengumumkan kepada dunia bahwa Republik Indonesia sudah hancur!</p>`,
      2: `<h2>PDRI, Perang Gerilya, dan Pengakuan Kedaulatan</h2>
      <p>Meskipun pemimpin tertangkap, Republik Indonesia tidak hancur! Sebelum ditangkap, Soekarno sempat mengirimkan kawat kepada Sjafruddin Prawiranegara di Sumatera untuk membentuk <strong>Pemerintah Darurat Republik Indonesia (PDRI)</strong>. PDRI inilah yang membuktikan kepada dunia bahwa pemerintahan Indonesia masih ada dan sah.</p>
      <p>Di lapangan, Panglima Besar Jenderal Soedirman yang sedang sakit paru-paru parah menolak menyerah. Beliau memimpin <strong>Perang Gerilya</strong> dengan cara ditandu keluar masuk hutan dan gunung. Strategi gerilya hit-and-run ini sangat merepotkan pasukan Belanda dan membuat moral mereka runtuh.</p>
      <p>Kombinasi antara tekanan diplomasi dari Perserikatan Bangsa-Bangsa (PBB) dan Amerika Serikat, serta kegigihan pasukan gerilya di lapangan, memaksa Belanda kembali ke meja perundingan. Akhirnya, melalui <strong>Konferensi Meja Bundar (KMB)</strong> di Den Haag pada akhir 1949, Belanda secara resmi "mengakui" kedaulatan Indonesia secara penuh dan tanpa syarat, meskipun dengan bentuk negara serikat (RIS) dan harus menanggung utang Hindia Belanda.</p>`,
      3: `<h2>Historiografi Revolusi: Dinamika Internal dan Konflik Ideologi</h2>
      <p>Mengkaji masa revolusi (1945-1949) secara komprehensif berarti kita tidak hanya melihat perang melawan Belanda (musuh eksternal), tetapi juga dinamika konflik berdarah di dalam tubuh bangsa sendiri (musuh internal). Revolusi Nasional seringkali berubah wujud menjadi Revolusi Sosial yang tidak terkendali.</p>
      <p>Di berbagai daerah seperti Sumatera Timur, Tiga Daerah, dan Banten, terjadi <em>Revolusi Sosial</em> di mana rakyat menggulingkan sultan dan raja-raja lokal yang dianggap feodal atau pernah bekerja sama dengan Belanda. Tragedi berdarah antar sesama anak bangsa tidak dapat dihindari.</p>
      <p>Selain itu, pemerintah pusat Republik Indonesia juga harus menghadapi tikaman dari belakang berupa dua pemberontakan ideologis besar di tengah agresi Belanda:</p>
      <p>1. <strong>Pemberontakan PKI Madiun (1948):</strong> Dipimpin oleh Musso dan Amir Sjarifuddin yang tidak puas dengan hasil Perjanjian Renville. Mereka memproklamasikan "Republik Soviet Indonesia" yang berideologi komunis di Madiun. Pasukan Siliwangi terpaksa ditarik dari garis depan untuk menumpas pemberontakan ini.</p>
      <p>2. <strong>Pemberontakan DI/TII Jawa Barat (1949):</strong> Dipimpin oleh S.M. Kartosuwiryo yang merasa dikhianati oleh pemerintah karena membiarkan wilayah Jawa Barat dikuasai Belanda akibat Perjanjian Renville. Ia memproklamasikan berdirinya Negara Islam Indonesia (NII).</p>
      <p>Dinamika ini menunjukkan betapa rapuhnya integrasi nasional di awal kemerdekaan, di mana para The Founding Fathers harus melakukan manuver <em>State-Building</em> sekaligus <em>Nation-Building</em> di bawah desingan peluru penjajah.</p>`
    }
  },
  {
    id: "chap_9",
    title: "Demokrasi Liberal & Demokrasi Terpimpin",
    summary: "Dinamika sistem pemerintahan pasca kemerdekaan, jatuh bangunnya kabinet parlementer, Pemilu 1955, hingga pemusatan kekuasaan dan tragedi 1965.",
    contentByLevel: {
      0: `<h2>Mencoba Demokrasi di Negara Baru</h2>
      <p>Setelah merdeka penuh pada tahun 1950, Indonesia kembali menjadi Negara Kesatuan (NKRI) dan mulai belajar berdemokrasi. Kita menggunakan sistem yang meniru negara-negara Eropa, yaitu Sistem Parlementer atau Demokrasi Liberal. Dalam sistem ini, negara memiliki sangat banyak partai politik (multipartai) dan pemerintahan dijalankan oleh seorang Perdana Menteri, sementara Presiden hanya sebagai kepala negara (simbol saja).</p>
      <p>Sayangnya, karena terlalu banyak partai yang saling berebut kekuasaan, pemerintahan tidak pernah stabil. Kabinet (menteri) sering ganti-ganti dalam waktu singkat. Ada 7 kabinet yang jatuh bangun hanya dalam waktu 9 tahun! Akibatnya, pembangunan jalan, sekolah, dan ekonomi menjadi terhambat karena program pemerintah tidak pernah selesai dijalankan.</p>
      <p>Melihat negara semakin kacau, Presiden Soekarno akhirnya mengambil langkah tegas. Pada tahun 1959, beliau mengeluarkan Dekrit Presiden yang mengembalikan Indonesia ke UUD 1945. Sistem negara berubah menjadi <strong>Demokrasi Terpimpin</strong>, di mana seluruh kekuasaan berpusat di tangan Bung Karno.</p>`,
      1: `<h2>Keberhasilan Pemilu 1955 dan Kegagalan Konstituante</h2>
      <p>Meskipun masa Demokrasi Liberal penuh dengan konflik politik, ada satu prestasi yang sangat membanggakan: <strong>Pemilihan Umum Pertama tahun 1955</strong>. Pemilu ini diakui sebagai pemilu paling jujur, adil, dan demokratis dalam sejarah Indonesia. Rakyat memilih wakil rakyat untuk DPR dan anggota Konstituante (badan yang bertugas membuat UUD baru pengganti UUDS 1950).</p>
      <p>Empat partai besar keluar sebagai pemenang Pemilu 1955, yaitu PNI, Masyumi, NU, dan PKI. Namun, anggota Konstituante hasil pemilu tersebut justru gagal membuat UUD baru. Mereka terus berdebat tanpa ujung (deadlock) mengenai dasar negara: kubu nasionalis ingin mempertahankan Pancasila, sedangkan kubu Islam ingin syariat Islam. Kebuntuan politik inilah yang membahayakan negara dan memicu keluarnya <strong>Dekrit Presiden 5 Juli 1959</strong>.</p>
      <p>Di masa Demokrasi Terpimpin, Presiden Soekarno memperkenalkan ajaran <strong>NASAKOM (Nasionalis, Agama, Komunis)</strong>. Tujuannya adalah untuk merangkul tiga kekuatan besar di Indonesia saat itu agar bisa bersatu membangun negara tanpa harus berkonflik ideologi terus-menerus.</p>`,
      2: `<h2>Politik Mercusuar dan Konfrontasi Global</h2>
      <p>Pada masa Demokrasi Terpimpin (1959-1965), arah politik Indonesia menjadi sangat radikal dan anti-Barat (anti-Imperialisme). Presiden Soekarno membagi kekuatan dunia menjadi dua: <em>Oldefo</em> (Old Established Forces / negara penjajah kapitalis) dan <em>Nefo</em> (New Emerging Forces / negara-negara baru merdeka yang anti-penjajah).</p>
      <p>Indonesia melakukan <strong>Politik Konfrontasi</strong> terhadap kekuatan yang dianggap boneka imperialis. Misalnya, operasi <strong>Trikora (Tri Komando Rakyat)</strong> untuk merebut kembali Irian Barat dari tangan Belanda. Kemudian disusul dengan operasi <strong>Dwikora (Dwi Komando Rakyat)</strong> dengan slogan "Ganyang Malaysia" karena menganggap pembentukan negara federasi Malaysia adalah proyek neokolonialisme Inggris yang mengancam kedaulatan Indonesia.</p>
      <p>Di dalam negeri, Soekarno melancarkan <strong>Politik Mercusuar</strong>. Beliau membangun proyek-proyek raksasa yang sangat megah seperti Monas, Stadion Utama Gelora Bung Karno, dan Masjid Istiqlal. Tujuannya agar Indonesia menjadi "mercusuar" (penerang) bagi negara-negara dunia ketiga dan disegani secara internasional, meskipun saat itu kondisi ekonomi rakyat sedang sangat terpuruk (inflasi mencapai 600%).</p>`,
      3: `<h2>Hegemoni Kekuasaan, Gesekan Elite, dan Tragedi 1965</h2>
      <p>Analisis mendalam terhadap Demokrasi Terpimpin menunjukkan sebuah sistem keseimbangan politik yang sangat rapuh. Kekuasaan berada di tangan Soekarno, namun beliau bertindak sebagai "juru damai" antara dua faksi besar yang saling bermusuhan secara ideologis: <strong>TNI Angkatan Darat</strong> (kekuatan militer yang anti-komunis) dan <strong>Partai Komunis Indonesia (PKI)</strong> (partai komunis terbesar ketiga di dunia setelah Uni Soviet dan Tiongkok).</p>
      <p>Ketegangan antara AD dan PKI semakin memuncak, terutama terkait usulan PKI untuk membentuk "Angkatan Kelima" (mempersenjatai buruh dan tani) yang ditolak mentah-mentah oleh petinggi Angkatan Darat.</p>
      <p>Puncak dari ketegangan ini adalah meletusnya tragedi berdarah <strong>Gerakan 30 September 1965 (G30S)</strong>. Sebanyak enam jenderal senior Angkatan Darat diculik dan dibunuh di Lubang Buaya dengan dalih ingin mencegah "Dewan Jenderal" yang akan melakukan kudeta. Mayor Jenderal Soeharto, selaku Panglima Kostrad, dengan cepat mengambil alih komando militer dan menumpas gerakan tersebut.</p>
      <p>Tragedi G30S memicu efek domino berupa pembersihan massal besar-besaran terhadap anggota PKI dan simpatisannya (diperkirakan setengah juta hingga satu juta orang tewas). Kondisi sosial-politik yang sangat kacau ini memaksa Presiden Soekarno mengeluarkan <strong>Surat Perintah Sebelas Maret (Supersemar) 1966</strong> kepada Soeharto. Supersemar menjadi titik balik peralihan hegemoni kekuasaan dari Orde Lama ke tangan Orde Baru yang militeristik.</p>`
    }
  },
  {
    id: "chap_10",
    title: "Orde Baru & Era Reformasi",
    summary: "Stabilitas politik dan pembangunan ekonomi pada era Soeharto, krisis moneter Asia 1997, runtuhnya rezim, dan tantangan transisi demokrasi.",
    contentByLevel: {
      0: `<h2>Era Pembangunan dan Stabilitas (Orde Baru)</h2>
      <p>Setelah Soeharto resmi menjadi Presiden kedua RI, dimulailah era yang disebut <strong>Orde Baru</strong> (1966-1998). Orde Baru memiliki semboyan untuk melaksanakan Pancasila dan UUD 1945 secara murni dan konsekuen. Di bawah kepemimpinan Pak Harto yang dijuluki "Bapak Pembangunan", Indonesia mengalami kemajuan infrastruktur yang sangat pesat. Banyak jalan tol, bendungan, rumah sakit, dan ribuan SD Inpres dibangun di pelosok desa.</p>
      <p>Ekonomi Indonesia yang sebelumnya hancur lebur bisa pulih kembali. Kebutuhan pokok seperti beras dan gula sangat mudah didapat dan harganya murah. Pada tahun 1984, Indonesia bahkan mendapat penghargaan dari FAO karena berhasil mencapai Swasembada Beras (bisa memproduksi beras sendiri tanpa perlu impor).</p>
      <p>Namun, semua kemajuan ekonomi itu harus dibayar mahal dengan "kebebasan". Di era Orde Baru, rakyat tidak boleh mengkritik pemerintah secara sembarangan. Jika ada koran yang mengkritik tajam, koran tersebut akan dibredel (ditutup paksa). Tidak ada kebebasan berpendapat seperti sekarang.</p>`,
      1: `<h2>Rekayasa Politik dan Dwifungsi ABRI</h2>
      <p>Kunci dari keberhasilan pembangunan ekonomi Orde Baru adalah <strong>Stabilitas Politik dan Keamanan</strong> yang dikontrol secara otoriter. Untuk menjaga agar tidak terjadi kegaduhan politik seperti masa Demokrasi Liberal, pemerintah melakukan penyederhanaan (fusi) partai politik pada tahun 1973 menjadi hanya tiga kelompok: PPP (Islam), PDI (Nasionalis), dan Golongan Karya (Golkar). Selama 32 tahun, Golkar selalu memenangkan pemilu secara mutlak dengan dukungan penuh birokrasi pemerintah.</p>
      <p>Selain itu, diberlakukan doktrin <strong>Dwifungsi ABRI</strong>. Tentara (TNI/Polri) tidak hanya bertugas sebagai alat pertahanan negara (kekuatan militer), tetapi juga memiliki peran sosial-politik. Artinya, militer berhak masuk ke pemerintahan, menjadi menteri, bupati, gubernur, bahkan anggota DPR tanpa harus melalui pemilu. Sistem ini membuat kekuasaan Presiden Soeharto ditopang kuat oleh kekuatan militer dari pusat hingga ke tingkat desa.</p>`,
      2: `<h2>Krisis Moneter 1997 dan Jatuhnya Rezim Orde Baru</h2>
      <p>Pembangunan ekonomi Orde Baru yang tampak kokoh ternyata keropos di dalamnya karena diliputi praktik <strong>KKN (Korupsi, Kolusi, dan Nepotisme)</strong>. Kepentingan bisnis hanya dikuasai oleh kroni (teman dekat) dan keluarga cendana. Ketika Krisis Finansial Asia (Krisis Moneter) melanda pada pertengahan tahun 1997, nilai tukar rupiah terhadap dolar Amerika hancur seketika (dari Rp 2.500 menjadi Rp 16.000 per dolar).</p>
      <p>Harga barang kebutuhan pokok melambung tinggi, perusahaan bangkrut massal, dan jutaan orang terkena PHK. Krisis ekonomi yang parah ini segera berubah menjadi Krisis Kepercayaan Rakyat. Mahasiswa dari berbagai universitas di seluruh Indonesia turun ke jalan melakukan demonstrasi besar-besaran (Gerakan Mahasiswa 1998) menuntut Tritura Baru (termasuk pemberantasan KKN dan Soeharto mundur).</p>
      <p>Keadaan semakin memburuk dengan terjadinya Tragedi Trisakti (empat mahasiswa tewas tertembak) dan kerusuhan massal pada 13-15 Mei 1998 di Jakarta dan beberapa kota lain. Akibat tekanan yang luar biasa dari berbagai pihak dan ditinggalkan oleh para menterinya sendiri, Presiden Soeharto akhirnya menyatakan <strong>Mundur / Berhenti</strong> sebagai Presiden RI pada tanggal <strong>21 Mei 1998</strong>, dan menyerahkan kekuasaan kepada BJ Habibie. Runtuhlah kekuasaan Orde Baru selama 32 tahun.</p>`,
      3: `<h2>Era Reformasi: Transisi Demokrasi dan Tantangan Global</h2>
      <p>Era pasca-Soeharto disebut sebagai <strong>Era Reformasi</strong>. Agenda utama reformasi adalah membongkar sistem otoritarian sentralistik menuju negara yang demokratis, bersih dari KKN, dan menegakkan supremasi hukum/HAM. Namun, masa transisi ini (pemerintahan Habibie, Gus Dur, dan Megawati) penuh dengan turbulensi politik yang hebat dan konflik komunal (SARA) di berbagai wilayah seperti Ambon, Poso, dan Sampit akibat longgarnya cengkeraman militer secara mendadak.</p>
      <p>Beberapa capaian fundamental (Structural Reform) berhasil dilakukan di masa transisi ini. <strong>Pertama</strong>, Amandemen UUD 1945 (dilakukan 4 kali) yang membatasi masa jabatan presiden menjadi maksimal dua periode (10 tahun), menghapus Dwifungsi ABRI, dan menciptakan lembaga-lembaga negara baru (seperti KPK dan Mahkamah Konstitusi). <strong>Kedua</strong>, kebijakan Otonomi Daerah (Desentralisasi) yang memberikan wewenang lebih besar kepada daerah untuk mengelola anggarannya sendiri, tidak lagi disedot habis oleh pusat (Jakarta).</p>
      <p><strong>Ketiga</strong>, kebebasan pers yang terjamin oleh undang-undang dan pelibatan rakyat secara langsung dalam politik (Pemilu Presiden Langsung pertama dilaksanakan tahun 2004). Tantangan historiografi kontemporer bagi Era Reformasi saat ini adalah konsolidasi institusi demokrasi yang berkualitas agar tidak dibajak kembali oleh oligarki politik-ekonomi, serta kemampuan adaptasi bangsa dalam menghadapi ancaman asimetris (post-truth, cyber warfare) di abad ke-21 tanpa mengorbankan pilar-pilar kebangsaan (Bhinneka Tunggal Ika).</p>`
    }
  }
];
